version: 2.1
jobs:
  regression_test_compatibility:
    docker:
      - image: python:3.6.4
        name: Python
        environment:
          HOST: 'http://hga66883.com'
          API_HOST: 'http://api.hga66883.com'
      - image: selenium/standalone-chrome:3.141.59
        name: selenium-chrome
      - image: selenium/standalone-firefox:3.141.59
        name: selenium-firefox
    steps:
      - checkout
      - run: python -m unittest test.GoogleChromeCompatibility
      - run: python -m unittest test.FirefoxCompatibility


workflows:
  version: 2
  pipeline:
    jobs:
      - regression_test_compatibility:
          pre-steps:
            - checkout
            - run: pip install -r requirements.txt
          filters:
            branches:
              only:
                - master